export const MANUAL_CONTENT = [
  {
    title: "1. Planung & Konfiguration",
    content: "Der Planer ist das zentrale Werkzeug zur Erstellung Ihrer Förderstrecke. Jeder Punkt kann individuell konfiguriert werden:\n\n## Kartenarbeit & GPS\n• Wegpunkte setzen: Einfacher Klick auf die Karte setzt einen neuen Punkt.\n• Wasserentnahme: Der erste gesetzte Punkt (Index 0) wird automatisch als Entnahmestelle definiert.\n• Abgabestelle: Der letzte Punkt der Kette ist das Ziel der Wasserförderung.\n• Marker verschieben: Halten und ziehen Sie einen Marker, um seine Position zu korrigieren.\n• Punkte einfügen: Klicken Sie auf die blaue Linie zwischen zwei Markern, um einen Zwischenpunkt einzufügen.\n• GPS-Tracking: Startet die automatische Aufzeichnung Ihres Weges. Alle 10m wird ein Punkt mit aktueller Höhe gesetzt.\n• Standort-Zentrierung: Das Fadenkreuz-Symbol springt sofort zu Ihrer aktuellen GPS-Position.\n• Kartenstile: Wechseln Sie in den Einstellungen zwischen Topografisch (Höhenlinien), Satellit oder Standard-OSM.\n• Route umkehren: Tauscht Start und Ziel der gesamten Planung inklusive aller Pumpen-Logik.\n\n## Pumpen- & Schlauch-Setup\n• Pumpenauswahl: Wählen Sie aus Ihrem Bestand. Die App zeigt nur aktivierte Modelle an.\n• Kennlinien: Bei Pumpen mit mehreren Stufen (z.B. 1600/3200 rpm) können Sie die Leistung wählen.\n• Pufferbecken: Setzt den Eingangsdruck an diesem Punkt auf 0 bar zurück (freier Auslauf).\n• Schlauch-Override: Ändern Sie für das folgende Segment den Schlauchtyp (z.B. von F auf H) oder die Anzahl der Leitungen.\n• Durchfluss (l/min): Der globale Durchfluss bestimmt den Reibungsverlust der gesamten Strecke.\n• Ausgangsdruck: Legen Sie fest, mit wie viel Druck das Wasser an der Entnahmestelle eingespeist wird.\n• Korndurchlass: Die App prüft, ob nachfolgende Pumpen einen kleineren Durchlass haben als vorherige (Verstopfungsgefahr)."
  },
  {
    title: "2. Analyse & Auswertung",
    content: "Die Auswertung visualisiert die physikalischen Grenzen Ihrer Planung und fasst die wichtigsten Parameter zusammen:\n\n## Kennwerte der Gesamtauswertung\n• Abgabedruck: Der berechnete Restdruck am Zielort (nur im Vorgabe-Modell sichtbar).\n• Volumenstrom: Die tatsächliche Förderleistung. Im Max. Flow Modell wird hier der berechnete Maximalwert angezeigt.\n• Distanz: Die Gesamtlänge der verlegten Schlauchleitung.\n• Höhendiff.: Der Netto-Höhenunterschied zwischen Wasserentnahme und Abgabe.\n• Druckverlust: Summe aller Verluste durch Reibung im Schlauch und geodätische Höhe.\n• Druck bei Nullförderung: Der maximale statische Druck bei geschlossenem Ausgang (Sicherheitswert).\n• Korndurchlass: Der kleinste freie Querschnitt in der Pumpenkette (Verstopfungsgefahr).\n• E. Leistung: Die theoretisch benötigte hydraulische Leistung für diese Förderung.\n• Pumpen-Überlast: Prüft, ob der gewählte oder berechnete Durchfluss die Kapazität der Pumpen überschreitet.\n\n## Physikalische Analyse\n• Druckgraph (Blau): Zeigt den berechneten Fließdruck an jeder Stelle der Leitung.\n• Unterdruck-Warnung: Sinkt der Druck unter **0 bar** (Rote Zone), bricht die Förderung ab (Kavitation/Schlauchkollaps).\n• Höhenprofil: Das Gelände wird 1:1 unter dem Graphen dargestellt.\n• Materialliste: Summiert alle benötigten Schläuche und Pumpenmodelle.\n• Interaktive Analyse: Klicken Sie in den Graphen, um die exakten Werte an dieser Stelle zu sehen."
  },
  {
    title: "3. Werkzeuge & Daten-Management",
    content: "Zusätzliche Funktionen zur Verwaltung und Dokumentation:\n\n## Dokumentation & Export\n• Strecken-Bibliothek: Speichern Sie Planungen lokal ab, um sie später wieder aufzurufen.\n• PDF-Einsatzplan: Generiert ein Dokument mit Karte, technischem Graph und Materialaufstellung.\n• Export: Laden Sie einzelne oder mehrere Strecken sowie Ihren Pumpenbestand als JSON-Datei herunter.\n• Import: Laden Sie zuvor exportierte JSON-Dateien hoch, um Strecken oder Pumpen in Ihre Bibliothek zu übernehmen.\n• Teilen per URL: Generieren Sie einen Link, der Ihre aktuelle Planung enthält. Jeder mit diesem Link kann Ihre Strecke direkt im Browser öffnen.\n• GPX-Schnittstelle: Importieren Sie Tracks aus Outdoor-Apps oder exportieren Sie Ihre Planung.\n• Löschfunktionen: Entfernen Sie einzelne Punkte, die gesamte Planung oder Ihre gespeicherte Bibliothek.\n\n## System & Einstellungen\n• Offline-Modus: Erkennt fehlendes Internet automatisch. Berechnungen und gecachte Höhendaten bleiben verfügbar.\n• Daten-Cache: Einmal geladene Höhendaten werden lokal gespeichert, um Datenvolumen zu sparen.\n\n## Berechnungs-Modelle (Einstellungen)\nIn den allgemeinen Einstellungen können Sie zwischen zwei Auswertungs-Modellen wählen:\n• **Vorgabe Modell**: Verwendet exakt den von Ihnen eingegebenen Volumenstrom. Ist die Strecke physikalisch nicht machbar, wird dies durch negativen Druck (Unterdruck) im Graphen und in den Warnungen angezeigt.\n• **Max. Flow Modell**: Berechnet automatisch den maximal möglichen Durchfluss, bei dem an allen Abgabestellen und Pufferbecken-Eingängen noch ein Sicherheits-Restdruck von mindestens **0,05 bar** anliegt."
  }
];
